# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # artifactory-orb: jfrog/artifactory-orb@1.0.1
  artifactory: circleci/artifactory@1.0.0

jobs:
  build:
    docker:
      - image: "circleci/node:10"
    steps:
      - checkout
      - artifactory/install
      - artifactory/configure
      - artifactory/build-integration

workflows:
  build:
    jobs:
      - build

  publish:
    jobs:
      - artifactory/upload:
          build-steps:
            - run: npm install
          name: Publish NPM
          source: circleciTest.tgz
          target: npmfrog/local
# jobs:
#   deploy:
#     working_directory: ~/repo
#     steps:
#       - checkout
#       - attach_workspace:
#           at: .

#           name: Install NPM
#           command: |
#             npm install
#       - run:
#           name: Install jFrog CLI
#           command: curl -fL https://getcli.jfrog.io | sh
#       - run:
#           name: Push to Artifactory
#           command: |
#             ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive=false
#             ./jfrog rt u <path/to/artifact> <artifactory_repo_name> --build-name=<name_you_give_to_build> --build-number=$CIRCLE_BUILD_NUM
#             ./jfrog rt bce <name_you_give_to_build> $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
#             ./jfrog rt bp <name_you_give_to_build> $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory

