# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # artifactory-orb: jfrog/artifactory-orb@1.0.1
#   artifactory: circleci/artifactory@1.0.0

# jobs:
#   build:
#     docker:
#       - image: "circleci/node:10"
#     steps:
#       - checkout
#       - artifactory/install
#       - artifactory/configure
#       - artifactory/build-integration

# workflows:
#   build:
#     jobs:
#       - build

#   publish:
#     jobs:
#       - artifactory/upload:
#           build-steps:
#             - run: npm install
#           name: Publish NPM
#           source: circleciTest.tgz
#           target: npmfrog/local

jobs:
  deploy:
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Push to Artifactory
          command: |
            ./jfrog config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_API_KEY --interactive=false
            ./jfrog  u local npmfrog --build-name=frogBuildTest
             --build-number=$CIRCLE_BUILD_NUM
            ./jfrog  bce frogBuildTest $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            ./jfrog  bp frogBuildTest $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory
